### ISSUE TITLE
Problem when using lnd_dir on init.

### ISSUE THREAD

**Issue by dgnsrekt** [willcl-ark/lnd_grpc#51]
/home/devtop/Programming/LIGHTNING/nox_lighting_playground/.lnd
TLS cert not found at /home/devtop/Programming/LIGHTNING/nox_lighting_playground/.lndtls.certTraceback (most recent call last):
  File "/home/devtop/Programming/LIGHTNING/nox_lighting_playground/core.py", line 9, in <module>
    print(x.get_info())
  File "/home/devtop/.local/share/virtualenvs/nox_lighting_playground-kQBQkvzH/lib/python3.7/site-packages/lnd_grpc/lightning.py", line 280, in get_info
    response = self.lightning_stub.GetInfo(request)
  File "/home/devtop/.local/share/virtualenvs/nox_lighting_playground-kQBQkvzH/lib/python3.7/site-packages/lnd_grpc/lightning.py", line 84, in lightning_stub
    credentials=self.combined_credentials,
  File "/home/devtop/.local/share/virtualenvs/nox_lighting_playground-kQBQkvzH/lib/python3.7/site-packages/lnd_grpc/base_client.py", line 144, in combined_credentials
    cert_creds = grpc.ssl_channel_credentials(self.tls_cert)
  File "/home/devtop/.local/share/virtualenvs/nox_lighting_playground-kQBQkvzH/lib/python3.7/site-packages/lnd_grpc/base_client.py", line 77, in tls_cert
    with open(self.tls_cert_path, 'rb') as r:
FileNotFoundError: [Errno 2] No such file or directory: '/home/devtop/Programming/LIGHTNING/nox_lighting_playground/.lndtls.cert'

**Comment by dgnsrekt** [comment]
```from lnd_grpc import Client
from pathlib import Path

root_path = Path(__file__).parent
lnd_path = root_path / ".lnd"
print(lnd_path)

x = Client(lnd_dir=str(lnd_path))
print(x.get_info())```
